---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

# namespace: my-namespace
# namePrefix: dev-
# nameSuffix: "-001"
# commonLabels:
#   app: bingo

commonAnnotations:
  policy.open-cluster-management.io/standards: Sandbox
  policy.open-cluster-management.io/categories: Binaries
  policy.open-cluster-management.io/controls: Catalogs