---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-disable-schedule-control
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-scheduling
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Scheduler
                metadata:
                  name: cluster
                spec:
                  mastersSchedulable: false
                  policy:
                    name: ""
