apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-olm-disable-defaults
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: olm-disable-defaults
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: config.openshift.io/v1
              kind: OperatorHub
              metadata:
                name: cluster
              spec:
                disableAllDefaultSources: true

