---
apiVersion: v1
kind: Secret
metadata:
  name: acmthanos
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acmthanos
      endpoint: s3.us-west-1.amazonaws.com
      signature_version2: false
      insecure: true
      access_key: ACCESSKEY1234567890
      secret_key: S3cr3tk3y
      http_config:
        insecure_skip_verify: false
