---
kind: Secret
apiVersion: v1
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
data:
  .dockerconfigjson: >-
    reallyLongBase64encPullSecret
type: kubernetes.io/dockerconfigjson