---
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  advanced:
    retentionConfig:
      retentionResolution1h: 30d
      retentionResolution5m: 14d
      retentionResolutionRaw: 5d
  enableDownsampling: false
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec:
    enableMetrics: true
    interval: 60
  storageConfig:
    alertmanagerStorageSize: 10Gi
    compactStorageSize: 10Gi
    metricObjectStorage:
      key: thanos.yaml
      name: acmthanos
    receiveStorageSize: 10Gi
    ruleStorageSize: 10Gi
    storageClass: gp2
    storeStorageSize: 10Gi